Repository untitled-team-101/Whiteboard, pull requests merged in 2021-10, with the labels that each got.

#25 fix: Shapes were drawn multiple times
  scripts/drawShapes.js
Labels: hacktoberfest-accepted, in-review

#24 add popup(modal) for downloading the board
  index.html
  scripts/download.js
  scripts/undoRedo.js
  styles/saveFilePopup.css
Labels: hacktoberfest-accepted

#28 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#20 Fix default colour mismatch #10
  index.html
  scripts/colorPicker.js
  scripts/drawShapes.js
Labels: in-review
